- package.json
- updated `files` property in package.json
> release 1.0.3

- src/map/core/AlloyMap.ts
Exposed some of drawInteraction functionality
> Exposed some of drawInteraction functionality

- package.json
- src/index.ts
- src/map/core/AlloyMap.ts
- src/map/layers/AlloyLayerWithFeatures.ts
- src/utils/ScreenshotUtils.ts
screenshot feature and visibility of classes
> release 1.0.6

- package.json
- src/map/basemaps/AlloyBasemapFactory.ts
fixes for basemap factory return type
> release 1.0.8

- src/map/styles/utils/AlloyBallUtils.ts
- src/map/styles/utils/AlloyIconUtils.ts
- src/map/styles/utils/AlloyLineUtils.ts
- src/map/styles/utils/AlloyPolygonUtils.ts
Don't know what really changed inside openlayers, but this now stops the icons stacking together on top of other styles
> added zIndex: 0 to all styles to enforce style render ordering

- src/map/basemaps/AlloyBasemapFactory.ts
The urls and tokens have timed out
> Updating the basemap mapbox urls

- src/map/interactions/AlloySelectionInteraction.ts
Fire features under selection when 1 feature selected with empty stack to fix multi overlay popup
> AL-3865 - Fire features under selection when 1 feature selected with empty stack

- src/map/core/AlloyMap.ts
- src/map/interactions/AlloySelectInPolygonInteraction.ts
filter function for startPolygonSelect
> AL-3683 - filter function for startPolygonSelect

- src/index.ts
- src/map/core/AlloyMap.ts
- src/map/guards/GeometryGuards.ts
- src/map/layers/AlloyLayerWithFeatures.ts
- src/map/layers/network/AlloyNetworkLayer.ts
- src/utils/FeatureUtils.ts
- src/utils/models/FindFeaturesWithinResult.ts
Find features near coordinate/geometry for AL-3972 and AL-3973
> Find features near coordinate/geometry for AL-3972 and AL-3973

- package-lock.json
- src/error/AlloyMapError.ts
> AL-4139 - Update AlloyMapError category from number to string

- src/map/core/AlloyBounds.ts
- src/map/core/AlloyMap.ts
- src/polyfills/PolyfillExtent.ts
- src/utils/FeatureUtils.ts
functionality to fit viewport around given features
> AL-4089 - functionality to fit viewport around given features

- src/index.ts
- src/map/features/AlloyCustomFeatureBase.ts
- src/map/features/AlloyCustomItemFeature.ts
- src/map/features/AlloyCustomItemFeatureFactory.ts
- src/map/features/AlloyCustomItemFeatureProperties.ts
- src/map/features/AlloyFeatureType.ts
- src/map/layers/custom/AlloyCustomLayer.ts
- src/map/layers/custom/AlloyCustomStyleProcessor.ts
- src/map/styles/builders/AlloyCustomStyleBuilder.ts
Changed AlloyCustomFeature to AlloyCustomFeatureBase that is extending by AlloyCustomFeature and AlloyCustomItemFeature
Added AlloyCustomItemFeature, Properties and Factory
> AL-4106 - AlloyCustomItemFeature implementation & AlloyCustomFeatureBase

- cypress/specs/test.spec.ts
- package-lock.json
I added an import for Chai `assert` at the top of the file because the version that Cypress comes with does not contain `exists` which checks if the value is `null` or `undefined`.
There is nothing that checks for undefined in the version of Chai that Cypress has, so I'd have to do:
`assert.true(!!array.find(a => a.id === id);`
Which is silly, versus:
`assert.exists(array.find(a => a.id === id);`
> Tests for the feature within function.

- src/map/basemaps/AlloyBasemapFactory.ts
- src/wms/WmsUtils.ts
Registering projection before creating WMS tile basemap, as otherwise tiles are requested with default 3857 projection
> AL-4632 - supporting WMS maps with unregistered projections

- src/map/features/AlloyWfsFeature.ts
- src/map/layers/wfs/AlloyWfsLayer.ts
- src/map/styles/builders/AlloyWfsStyleBuilder.ts
- src/utils/FeatureUtils.ts
- src/wfs/WfsFeatureProperty.ts
- src/wfs/WfsLayerUtils.ts
- src/wfs/WfsUtils.ts
Fix for displaying WFS style
disabled FeatureDescriptions
Fix for polygon icons in WFS style builder
Check that projection is registered before requesting features
> AL-4559 - WFS fixes

- package-lock.json
- package.json
- src/map/basemaps/AlloyTileBasemap.ts
- src/wms/WmsUtils.ts
added DOMPurify library to sanitise HTML for basemap watermarks
> AL-4590 - added DOMPurify library to sanitise HTML for basemap watermarks

- src/map/layers/cable/AlloyCableAnimationManager.ts
- src/map/layers/route/AlloyRouteAnimationManager.ts
Instead of re-building geometry on every render for every position, added a default shape geometry that gets cloned, rotated, scaled and positioned.
Replaced geometry wrapping with feature for `renderer.drawFeature`, with `renderer.setStyle` and `renderer.drawGeometry`
> AL-5866 - fix for animation memory issue

- src/map/basemaps/AlloyBingBasemap.ts
Updated Bing satellite map to use newest tiles, added support for hiDpi tiles
> Update for Bing satellite basemap

- src/map/basemaps/AlloyBasemapFactory.ts
- src/wms/AlloyWmsCapabilitiesLayer.ts
- src/wms/WmsUtils.ts
- src/wmts/AlloyWmtsCapabilitiesLayer.ts
- src/wmts/AlloyWmtsParameters.ts
- src/wmts/WmtsUtils.ts
so what's used for requests can be selected and passed back in AlloyWmsParameters (crs) and AlloyWmtsParameters (tileMatrixId)
> AL-5854 - returning all available crs for WMS and WMTS layers

- src/wms/WmsUtils.ts
Fix for WMS capabilities query string params
> AL-6133 - fix for WMS capabilities query string params

- package-lock.json
- package.json
- src/map/styles/builders/AlloyCustomStyleBuilder.ts
- src/map/styles/builders/AlloyItemStyleBuilder.ts
- src/map/styles/builders/AlloyNetworkStyleBuilder.ts
- src/map/styles/builders/AlloyWfsStyleBuilder.ts
- src/map/styles/utils/geometry-functions/AlloyMultiLineStringFunctions.ts
Fix for labels for features with MultiLineString geometries
> Label fix for MultiLineString geometries

- src/map/core/AlloyMap.ts
- src/map/core/AlloyMapOptions.ts
- src/map/features/AlloyAnimatedPathFeature.ts
- src/map/interactions/AlloySelectionInteraction.ts
- src/map/layers/animation/AlloyAnimatedPathLayer.ts
- src/map/layers/route/AlloyRouteLayer.ts
- src/utils/ScreenshotUtils.ts
Fix for routing
Selection interaction ignore features that are not selectable (before multi feature overlay would not come up if top feature is not selectable)
Added map option to hide scale
> Update for routing

- src/utils/ScreenshotUtils.ts
Fix for map screenshot util to work with multiple map canvases which openlayers adds for hiDpi screens
> AL-6508 - Fix for screenshot utils on hiDpi screens

- src/map/basemaps/AlloyBasemapFactory.ts
Basemap projection registering cleanup.
> AL-6216 - basemap projection registering cleanup

- src/map/interactions/AlloyDrawInteraction.ts
- src/map/layers/drawing/AlloyDrawLayer.ts
- src/map/styles/builders/AlloyDrawStyleBuilder.ts
- src/map/styles/utils/geometry-functions/AlloyGeometryCollectionFunctions.ts
- src/map/styles/utils/geometry-functions/AlloyMultiPolygonFunctions.ts
- src/utils/GeometryUtils.ts
Fix for multi-geometry editing.
Fix for icon displaying on largest polygon.
> AL-6557 - fix for multi-geometry editing

- src/map/interactions/AlloyDrawInteraction.ts
- src/map/interactions/AlloyDrawInteractionGeometryType.ts
- src/utils/EnumUtils.ts
https://streamable.com/gurznf
The icon is missing because running local with no font files.
> adding support for box drawing

- .eslintrc.json
- cypress/specs/all/wfs/blaby_gov_uk_WFS_GetCapabilitiesParsed.json
- cypress/specs/all/wfs/bristol_gov_uk_WFS_GetCapabilitiesParsed.json
- cypress/specs/all/wfs/gov_wales_WFS_GetCapabilitiesParsed.json
- src/index.ts
- src/map/layers/wfs/AlloyWfsLayer.ts
- src/map/styles/AlloyWfsLayerStyle.ts
- src/wfs/AlloyWfsCapabilities.ts
- src/wfs/AlloyWfsFormat.ts
- src/wfs/WfsLayerUtils.ts
- src/wfs/WfsUtils.ts
- src/wfs/WfsVersionParser.ts
- www/examples/wfs.html
Support for WFS output formats - GeoJson, EsriJSON, KML, GML 2, GML 3
> AL-7157 - support for different WFS output formats

- src/map/features/AlloyWfsFeature.ts
- src/map/layers/wfs/AlloyWfsLayer.ts
- src/map/styles/builders/AlloyWfsStyleBuilder.ts
- src/map/styles/utils/AlloyLabelUtils.ts
- src/wfs/WfsLayerUtils.ts
- src/wfs/WfsUtils.ts
- Get WFS description for styleId
- Displaying faded polygon when label title is not present but subtitle is, only for title+subtitle label mode
- WFS style handling numeric properties in labels
- Support for feature geometry in WfsFeatureProperties
> AL-7646 - WFS fixes

- src/map/core/AlloyMap.ts
- src/map/interactions/AlloyDrawInteraction.ts
- src/map/layers/drawing/AlloyDrawLayer.ts
- src/utils/GeometryUtils.ts
- Better handling of coordinate and feature removal from draw interaction
- Better wrapping of all draw geometries into GeometryCollection
- changed `olMap.setTarget(null as any)` to `olMap.setTarget(undefined)`
> AL-7699 - draw interaction fixes

- package-lock.json
- src/index.ts
- src/map/core/AlloyHoverMode.ts
- src/map/core/AlloyMap.ts
- src/map/interactions/AlloyHoverInteraction.ts
- src/map/layers/AlloyLayer.ts
- src/map/layers/AlloyLayerWithFeatures.ts
- src/map/layers/AlloyLayerWithFeaturesWithItemId.ts
- src/map/layers/animation/AlloyAnimatedPathLayer.ts
- src/map/layers/basic/AlloyBasicLayer.ts
- src/map/layers/cable/AlloyCableLayer.ts
- src/map/layers/cluster/AlloyClusterLayer.ts
- src/map/layers/custom/AlloyCustomLayer.ts
- src/map/layers/drawing/AlloyDrawLayer.ts
- src/map/layers/hover/AlloyHoverLayer.ts
- src/map/layers/network/AlloyNetworkLayer.ts
- src/map/layers/route/AlloyRouteLayer.ts
- src/map/layers/selection/AlloySelectionLayer.ts
- src/map/layers/wfs/AlloyWfsLayer.ts
- src/map/layers/wms/AlloyWmsLayer.ts
- Added AlloyHoverMode for map that enables/disables hover interaction
- Added clone functionality to layers so that they can be cloned onto a different map instance
- Added isInternalLayer function to layers to check whether layer is internal (for selection/hover/draw interactions) or external
> AL-8738 - map hover mode, layers clone, layers internal/external check

- src/wmts/AlloyWmtsCapabilitiesLayer.ts
- src/wmts/WmtsLayer.ts
- src/wmts/WmtsUtils.ts
First try and pick png or jpeg format if possible, otherwise use default
> AL-9019 - WMTS formats fix

- src/map/interactions/AlloyDrawInteraction.ts
- src/map/layers/AlloyLayer.ts
- src/map/layers/AlloyLayerWithFeatures.ts
- src/map/layers/AlloyLayerWithFeaturesWithItemId.ts
- src/map/layers/animation/AlloyAnimatedPathLayer.ts
- src/map/layers/basic/AlloyBasicLayer.ts
- src/map/layers/cluster/AlloyClusterLayer.ts
- src/map/layers/custom/AlloyCustomLayer.ts
- src/map/layers/drawing/AlloyDrawLayer.ts
- src/map/layers/hover/AlloyHoverLayer.ts
- src/map/layers/network/AlloyNetworkLayer.ts
- src/map/layers/selection/AlloySelectionLayer.ts
- src/map/layers/wfs/AlloyWfsLayer.ts
- src/map/layers/wms/AlloyWmsLayer.ts
- Adding draw layer olLayers to olMap directly so that draw layers are not in the map's managed layers map
- Removed isInternalLayer flag from layers
> AL-9051 - draw layers and isInternalLayer fix

- src/map/interactions/AlloySelectInPolygonInteraction.ts
When selecting features using polygon selection take into account features in the selection layer
> AL-8906 - polygon select take into account features in selection layer
